### ISSUE TITLE
documentation + dockerization + business enquiry

### ISSUE THREAD

**Issue by rsingh888** [Anga205/AngaDriveV2#42]
Hi,
Can you please explain me 
- How and why should one use this repo? Was not able to understand key feature its offering
- what's your plan to distribute it?
- Can you dockerize this as I host most of my stuff on caprover, if you are ok I dont mind creating a branch and dockerize this myself for you to merge later
- whats the licensing model (MIT, AGPL , GPL etc)

thanks
rajeev

**Comment by Anga205** [comment]
> How and why should one use this repo? Was not able to understand key feature its offering

my mistake, ill improve documentation to explain better how and why this repo can be used, at its base it is a remote file hosting web application, its the code that has currently been deployed on [this website](https://drive.anga.pro/) i usually use it to store and share pictures, videos and documents

> whats your plan to distribute it?

the code itself isnt really for commericial purposes, its just the repository for the angadrive website, which i created because my google drive was running out of space and i didnt want to pay for google one, i never intended to distribute or profit off this code

> Can you dockerize this as I host most of my stuff on caprover, if you are ok I dont mind creating a branch and dockerize this myself for you to merge later

any and all meaningful pull requests and contributions are more than welcome! and yes, i can dockerize this code, its just a short python script that runs on a raspberry pi so i never felt the need to dockerize it

> whats the licensing model (MIT, AGPL , GPL etc)

ill add one
